### ISSUE TITLE
downloading new miner after update in .ps1

### ISSUE THREAD

**Issue by rinkal26783** [MrPlusGH/NPlusMiner#106]
Whenever i disable some algo in any miner. It downloads that miner again.

**Comment by MrPlusGH** [comment]
This is expected behavior.
NPlusMiner detects changes in miner files and redownloads the binaries when detected.
This is an improvement from the previous versions where binaries where not downloaded on miners version upgrade.
It plays well with AutoUpdate.
The impacts of redownloading after file change is minimal.
