### ISSUE TITLE
Ability to disable specific mining software

### ISSUE THREAD

**Issue by covah22** [MrPlusGH/NPlusMiner#191]
Hello, I have a few different mining rigs, one of them has an older video card (AMD 290), and it's no longer supported by Teamred. How can I disable this miner from loading in NPlusMiner?

I'm currently stuck in a loop on that system that constantly attempts Teamred (from my understanding, 3 times per algo), fails, stops reporting a benchmarking result of 0 and then it loads teamred again. 

I've attempted to put the config mode into manual mode, and remove any listings of Teamred, but to no avail.

Thank you for your time and thank you for this miner! It's damn impressive!

**Comment by grantemsley** [comment]
There are settings for it here: https://github.com/MrPlusGH/NPlusMiner-Documentation/wiki/Custom-Miner-Configuration-(advanced), but I think you have to specify every algorithm the miner uses since it says algorithm is a required field for the rules.

If you can't figure that out, you can just delete that miner - go into the Miners folder and delete TeamRed.ps1 - that will remove the miner from the list of available options so it never tries it again. May have to do that again after each update.

**Comment by johnrando** [comment]
a temporary fix is to delete that miner's .ps1 file from the miners folder, though be aware that it will get copied back in place when NPlusMiner updates.

**Comment by covah22** [comment]
Thank you both I appreciate the assistance. I did previously delete the Teamred.ps1 file, but I must have caught it just after an update as it instantly started downloading it again. >.<

But it worked this time haha Thank you!

I'll look through the advanced documentation again and see if there is an easier way to do so. If not, I'll probably just script an auto delete teamred.ps1 after an update or something.

Thanks again

**Comment by MrPlusGH** [comment]
You can add a MinerCustomConfig rule with return in the code area.
