### ISSUE TITLE
Earnings Tracking Error

### ISSUE THREAD

**Issue by liquidone** [MrPlusGH/NPlusMiner#2]
Hi,

   Please look at the screenshot. I am getting a similar error on 2 different rigs. Not sure how to resolve it or what it stems from.

Great project by the way!
![earnings error](https://user-images.githubusercontent.com/35848125/36572143-5e410e5e-17f7-11e8-9632-2afd2bee930e.jpg)

**Comment by MrPlusGH** [comment]
Error not handled properly when API call fails.
Check if occurrence of Threshold being null which should never be for supported pools. (double check)

Will fix in next version.

**Comment by nemosminer** [comment]
bug fix for that:

https://github.com/nemosminer/NemosMiner-v2.5/issues/313

https://github.com/nemosminer/NemosMiner-v2.5/commit/001aa13964a48c3d56baf6eb17380b60c2084752

**Comment by liquidone** [comment]
Fantastic, thank you! 

It's been driving me nuts for the last few days :)

**Comment by MrPlusGH** [comment]
Thanks Nemo. I really like our collaboration!

This is more of a workaround than a fix. That's a great solution until I find the root cause.
The payment threshold is not coming from the pool but from our service that I maintain. So this should never be 0 and even if so. The code should resist to this.
Note that some people reporting this issues were referring MPH and hashrefinery which are not yet supported for earning tracker. (see readme)
However, some reported for zpool which is supported so I'll investigate on this one.

Keeping opened as bug for now.

**Comment by liquidone** [comment]
I'm using the current master an on all rigs, across 3 different pools zpool,ahash and zerg and I am seeing "Automatic Payouts Disabled" on all of them.

the error is gone but earnings tracking still doesn't appear to be working.

**Comment by MrPlusGH** [comment]
Implemented fix on master.
Would be great if you could test and report.

Will properly ignore unsupported pools.
Will properly ignore when webservice failure.

**Comment by liquidone** [comment]
ok I will go ahead and test and report now :)  Thanks for all your help!

**Comment by liquidone** [comment]
Just to be clear, earnings data will not show until Trust = 100% ?   Is that correct?
