### ISSUE TITLE
ZergPoolCoinsPlus?

### ISSUE THREAD

**Issue by gak45** [MrPlusGH/NPlusMiner#61]
Any chance of adding in ZergPoolCoins, and maybe ZergPoolCoinsPlus pool options? Would be nice to not have to mine crap coins along with profitable ones. :)

**Comment by nsummy** [comment]
What is zergpoolcoins?

**Comment by Tesla74** [comment]
https://github.com/nemosminer/NemosMiner/issues/408

**Comment by ebojali** [comment]
I put my vote on this enhancement as well 👍

**Comment by nsummy** [comment]
Doesn't the Plus algorithm kind of render this feature redundant?

**Comment by ebojali** [comment]
Did not read the code for the plus functionality so I am not sure but by looking at my wallet I can see I do not mine the most profitable coin for that algo.. (lyra2v2)..mobilecash instead of Mona..

![screenshot_20180418-205100](https://user-images.githubusercontent.com/35561346/38952017-9059a7b0-434a-11e8-82ab-9d27972ddae9.png)
![screenshot_20180418-205046](https://user-images.githubusercontent.com/35561346/38952028-967ea320-434a-11e8-8035-d8562282480f.png)

**Comment by gak45** [comment]
The plus pool feature just mines the most optimal _algorithm_. Not the most profitable _coin_ on said alog. With the extra data a pluscoin feature could offer it would not only make overall profits higher but make the 'brains' feature (that makes the pool plus option work) even smarter. Win-win. :)

**Comment by ebojali** [comment]
Me like! ✌️

**Comment by nemosminer** [comment]
@ebojali it is does always mine the most profitable coin at that time its mining mona... 
it has the full pool hashrate on mona...

you said
"mobilecash instead of Mona.."
you are incorrect.. 

its is mining  mona.... mobilecash is being merged mined....
