### ISSUE TITLE
LTC/day shows as BTC/day

### ISSUE THREAD

**Issue by ebojali** [MrPlusGH/NPlusMiner#63]
Is the a problem with BTC/day in the summary printout? NplusMiner 2.2 is not showing me anything for that row. See pic below.
![screenshot_20180411-173252](https://user-images.githubusercontent.com/35561346/38627226-c6212270-3dae-11e8-8d99-8d90c3c6114e.png)

**Comment by MrPlusGH** [comment]
does it show in the GUI?

**Comment by ebojali** [comment]
Like this, but not showing realistic values. Does it support several wallers as I put both BTC for some pools and LTC for others in the config plus file..
![screenshot_20180412-091854](https://user-images.githubusercontent.com/35561346/38661966-02e49d0c-3e33-11e8-80af-4875130c278d.png)

**Comment by MrPlusGH** [comment]
It works. (sort of :S )
Your earnings are in LTC for the pools set to LTC, just the column names are hard coded to BTC.
The balance shown is in LTC as well.

So if you read LTC instead of BTC for the first two rows, you're good.

Of course, the total is off as we're adding BTCs and LTCs :(

Earnings Tracker in currency others than BTC is part of the things I do have to improve. 

This does not explain the blank values in the console... I have to investigate this one...

**Comment by ebojali** [comment]
@MrPlusGH  Thanks alot man.. I really like you miner and I've order an i3 processor for this to see if I could get rid of my latest problem. 

II know it showas ok in the UI, but do you have any update on the console printout since I am a console freak and want to get everything printed out :)

**Comment by MrPlusGH** [comment]
Console will be fixed in next version.
Fixed in dev.
