### ISSUE TITLE
When are you planning to release a new version?

### ISSUE THREAD

**Issue by ebojali** [MrPlusGH/NPlusMiner#69]
Hi,

There are some interesting fixes that I know I would love to have, when are you planning to release a new version of NplusMiner?

Cheers
//Bojan

**Comment by MrPlusGH** [comment]
New version is in final testing. Should be coming this week or the next.
Any details on fixes you are expecting?

**Comment by rander2009** [comment]
Not sure if it's a fix or more an enhancement - some sort of averaging mechanism for x16x algorithm performance/benchmarks would be great. 

Sent from MailDroid

-----Original Message-----

**Comment by Tesla74** [comment]
X16r should be averaged over an hour, but not a problem with X16s.
https://i1.wp.com/coinguides.org/wp-content/uploads/2018/04/x16r-vs-x16s.png?w=628&ssl=1

**Comment by rander2009** [comment]
Wow, are you sure those are right? As example I have machine with 10 1080ti, it ranges from 170 to 225.  Can't remeber if it's on x16s or x16r

Sent from MailDroid

-----Original Message-----

**Comment by Tesla74** [comment]
Source: Pigeoncoin

**Comment by rander2009** [comment]
Yea....  I'll see if I can find some data.. 

Sent from MailDroid

-----Original Message-----

**Comment by rander2009** [comment]
Maybe this is from the pool side, as opposed to the miner? 

Sent from MailDroid

-----Original Message-----

**Comment by Tesla74** [comment]
I would check to see if you're mining s or r.  As far as I know it is only a problem with r.

**Comment by rander2009** [comment]
Sent from MailDroid

-----Original Message-----

**Comment by rander2009** [comment]
Just checked x16r ranged from 164 (now) with a high of 209 earlier today running on ahashpool

Sent from MailDroid

-----Original Message-----

**Comment by rander2009** [comment]
From ZENEMY 109 read me

 

This release is reported to be more stable when it comes to higher PL or overclocking, feel free to experiment with it.

______________________________________

First time or troubleshooting x16:

-   First time users - ver. 1.08 works on Cuda 9.1 and it is recommended to make sure you've updated your NVIDIA drivers. You can find drivers here:  <http://www.nvidia.com/Download/index.aspx> http://www.nvidia.com/Download/index.aspx ver., 390+++

-   Next important thing is intensity. We recommend intensity -19 at first, however if your PC has 8GB or more, fast SSD, and big swap file on it you may use -20/21.

-   X16r algo is very wild and eratic.  *Very important*  Make sure to have enough power reserve on PSU. Please be sure you have a minimum 20% headroom on your PSU or set your PL on 70-80% usage.

-   Using +core and +mem is useful but, use no OC at first until you verify stability. 

 

 

Performance and fine tuning x16: 

-   This release z-enemy 1.08 is reported to be more stable when it using higher PL (90-110%) and +core and +memory overclocking, feel free to experiment with it.

-   Updating drivers can provide more gains

-   Recommended intensity is 20, set 21 only if you know what you are doing. ( 16GB RAM or/and good SWAP file on SSD) Use caution

-   Recommended memory   0 or +

-   Recommended core +50+150 ( 1800-1900MHz 1080 Ti)

-   Overclock slowly and allow plenty of time to verify stability (12-24hrs) before making anymore adjustments. x16r is a very chaotic algorithm so just because it works for 1 hr doesn't mean you can't crash over longer time. Sometimes hash order can lead to 2000+mhz and crash system. Keep in mind – overclocking is always at your own risk!

-   Yiimp pools recommend  manual diff (-p d=16) - for  small farms or  (-p d=48 ) - for good farms like 5-6 1080 Ti   If you need to name your rigs as well as set diff you may try -p rigname,d=16

**Comment by ebojali** [comment]
@MrPlusGH  any release soon?

**Comment by MrPlusGH** [comment]
I'm late on my release plan. Next version is going through code cleaning and packaging and should be available soon.

**Comment by rander2009** [comment]
Can you tease us with list of new features? 

Sent from MailDroid

-----Original Message-----

**Comment by Tesla74** [comment]
I was starting to worry that the project wasn't active anymore.  Glad to know you're still working on it.  No rush.

**Comment by ebojali** [comment]
Still nothing?  I noticed that NplusMiner fall a bit behind when it comes to miners.. I hope new version and new better miners will be added.

**Comment by MrPlusGH** [comment]
Miners and Pools update will follow @nemosminer work.

Non exhaustive list of next version features:

- Responsive GUI
   - No more "Not responding" or "spinning donut".
   - Fixed GUI lags 
- Optimized memory management
   - NPlusMiner could have been consuming a lot of memory after a long runtime (~2Gb !). We fix code and NPlusMiner comsumes less memory after long runtime.
- AutoUpdate feature
- BrainPlus Jobs start
   - Previously, BrainPlus jobs were only started at startup. BrainPlus jobs are now started when required. This avoid the need for an application restart when adding Plus pools in config. Simply add the Plus pool you want at runtime, hit Save Config and wait for the next cycle.
-  Earnings Tracker Jobs start
   - Previously, Earning Tracker jobs were only started at startup. Earning Tracker jobs are now started when required. This avoid the need for an application restart when adding Plus pools in config. Simply add the Plus pool you want at runtime, hit Save Config and wait for the next cycle.
- CPU mining (experimental)
- Multi Instance Improvement
   - Port detection now has no impact on running miners.
   - Multi Instance still requires two separated copies of NPlusMiner in different folders.
- Fixed wrong GPU selection on first running
   - NPLusMiner was selecting the wrong list of GPU after GPU count detection on first run only. This is now fixed.
- ...

**Comment by Tesla74** [comment]
Thanks for the update!

**Comment by MrPlusGH** [comment]
#78 Master = 4.0 for testers
